apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender
spec:
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
      - name: sender
        image: emanuelfeijo/redis-pub-sender:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sender
spec:
  selector:
    app: sender
  ports:
  - port: 9090
    protocol: TCP
